# Generated by Django 5.2 on 2025-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='origin',
            new_name='driver_name',
            
        ),
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='rideparticipant',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='rideparticipant',
            name='checked_out',
        ),
        migrations.AddField(
            model_name='ride',
            name='source',
            field=models.CharField(default='Campus', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
